ip = "192.168.178.170:1234"

[commands]
generic = { help = "Receive generic datagrams", cmds = ["$pfilt,0,1**_****_****"] }
specific = { help = "Receive specific datagrams", cmds = ["$pfilt,0,0**_****_****"] }
