[package]
name = "termtest"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
smol = "2.0.2"
toml = "0.9.5"
