[package]
name = "corelib"
version = "0.1.0"
edition = "2024"

[dependencies]
heapless = "0.8.0"
embassy-time        = { version = "0.4.0", features = [] }
embassy-sync        = { version = "0.6.2", features = [] }
